# A script to import contacts and messages from sqlite3 dump generated by the
# https://github.com/ostankin/mirandat3 script
#
# Usage:
# python3 scripts/miranda/import-miranda-sqlite3-dump.py contacts -d export.sqlite3 > contacts.json
# python3 scripts/miranda/import-miranda-sqlite3-dump.py messages -d export.sqlite3 -u <user_uin> > messages.json

import argparse
from datetime import datetime
import json
from vendor.mirandat3.mirandat3 import DBHeader, DBContact, Encoder

def get_platform(p):
    if p == 'JABBER':
        return 'jabber'
    return p

def get_contact(c: DBContact):
    name = str(c.name)
    settings = {}
    for k, v in list(c.settings.items()):
        v = v.decode('utf-8') if isinstance(v, bytes) else str(v)
        settings[k] = v
    return {
        "name": name,
        "platform_ids": [{
            "id": settings.setdefault("UIN", "UNKNOWN"),
            "platform": get_platform(settings["p"]),
            "avatar": "",
            "meta": settings
        }]
    }

def get_messages(c: DBContact, owner_name):
    platform = get_platform(c.settings.get("p"))
    contact_name = str(c.name)
    messages = []
    for e in c.events:
        if e.dir() == '>':
            m_from = contact_name
            m_to = {"type": "user", "user_id": owner_name}
        else:
            m_from = owner_name
            m_to = {"type": "user", "user_id": contact_name}
        messages.append({
            "platform": get_platform(platform),
            "ts": e.timestamp.isoformat(),
            "from": m_from,
            "to": m_to,
            "text": e.parse_blob(),
            "raw": None,
            "attachments": [],
            "meta": {
                "type": e.typestr()
            }
        })

    return messages


def main():
    parser = argparse.ArgumentParser(description="Import contacts and messages from Miranda SQLite dump")
    parser.add_argument("mode", choices=["contacts", "messages"], help="Mode: contacts or messages")
    parser.add_argument("-f", "--file", required=True, help="MirandaIM dat file")
    parser.add_argument("-u", "--user", help="Name of the use (for message mode)")
    parser.add_argument("-e", "--encoding", help="Encoding code page", default=Encoder.encoding)

    args = parser.parse_args()
    owner_name = "unknown"
    if args.user:
        owner_name = args.user

    Encoder.encoding = args.encoding

    dat = None
    with open(args.file, 'rb') as f:
        dat = f.read()
    header = DBHeader(dat)

    next_contact = header.firstContact
    contacts = []
    messages = []
    while next_contact != 0:
        c = DBContact(dat, next_contact)
        contacts.append(get_contact(c))
        if args.mode == "messages":
            messages += get_messages(c, owner_name)
        next_contact = c.next

    if args.mode == "contacts":
        print(json.dumps(contacts, indent=2, ensure_ascii=False))
    if args.mode == "messages":
        print(json.dumps(messages, indent=2, ensure_ascii=False))

        # cur.execute("insert into contacts(name) values (?)", (str(c.name).encode('utf-8'),))
        # c_id = None
        # for row in cur.execute('select last_insert_rowid()'):
        #     print(row)
        #     c_id = row[0]
        # cur.executemany("insert into settings(owner, name, value) values (?, ?, ?)",
        #                 [(c_id, k.encode('utf-8'), str(v).encode('utf-8')) for k, v in list(c.settings.items())])
        # cur.executemany("insert into events(owner, direction, timestamp, type, data) values (?, ?, ?, ?, ?)",
        #                 [(c_id, e.dir() ,e.timestamp, e.typestr().encode('utf-8'), e.parse_blob().encode('utf-8')) for e in c.events])
        # next_contact = c.next




if __name__ == "__main__":
    main()